pipeline {
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'user')
    }

    stages {
        stage('SCM') {
            steps {
                sh "echo 'SCM...'"
                checkout scm
            }
        }

        stage('Springboot build'){
            steps{
                dir('backend/user'){
                    sh '''
                    echo 'Springboot build...'
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
        }

        stage('Dockerimage build'){
            steps {
                dir('backend/user') {
                    script {
                        def containerExists = sh(script: "docker ps -a --format '{{.Names}}' | grep ${params.NAME}", returnStatus: true) == 0

                        if (containerExists) {
                            sh "docker stop ${params.NAME}"
                            sh "docker rm ${params.NAME}"
                            sh "docker rmi hyunjinius/user:latest"
                        }


                        sh '''
                        echo 'Dockerimage build...'
                        docker build -t hyunjinius/user:latest .
                        '''
                    }
                }
            }
        }

        stage('Deploy'){
            steps{
                dir('backend/user'){
                    sh '''
                    echo 'Deploy BE...'
                    docker run -d -p 0:8082 --env-file ./.env --name user hyunjinius/user:latest
                    '''
                }
            }
        }
    }
}