pipeline {
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'vue')
    }

    tools {
        nodejs 'Node20'
    }

    stages {
        stage('Vue build'){
            steps{
                dir('frontend/piece'){
                    echo 'Vue build...'
                    sh 'npm install'
                    sh 'CI=false npm run build'
                }
            }
        }
    }

    post {
        success {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'good',
                message: "##  :velkoz: #${env.BUILD_NUMBER} 빌드 성공 !! ${env.JOB_NAME}\n${Author_ID} (<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/dk7sbx6mmbdp8yignuknexyagh',
                channel: 'jenkins202'
//              icon: 'https://www.pngfind.com/pngs/m/437-4370721_61-kb-png-pepe-giving-thumbs-up-transparent.png'
                )
            }
        }

        failure {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'danger',
                message: "##  :badgun: #${env.BUILD_NUMBER} 빌드 실패 ㅜㅜ ${env.JOB_NAME}\n${Author_ID} (<${env.BUILD_URL}|Details>)",
                endpoint: 'https://meeting.ssafy.com/hooks/dk7sbx6mmbdp8yignuknexyagh',
                channel: 'jenkins202'
//              icon: 'https://www.iconspng.com/images/sad-pepe-feelsbadman.jpg',
                )
            }
        }
    }
}
