pipeline {
    agent any

    parameters{
        string(name: 'NAME', defaultValue: 'piece')
    }

    stages {
        stage('SCM') {
            steps {
                sh "echo 'SCM...'"
                checkout scm
            }
        }

        stage('Springboot build'){
            steps{
                dir('backend/piece'){
                    sh '''
                    echo 'Springboot build...'
                    chmod +x gradlew
                    ./gradlew clean build
                    '''
                }
            }
        }

        stage('Dockerimage build'){
            steps {
                dir('backend/piece') {
                    script {
                        def containerExists = sh(script: "docker ps -a --format '{{.Names}}' | grep ${params.NAME}", returnStatus: true) == 0

                        if (containerExists) {
                            sh "docker stop ${params.NAME}"
                            sh "docker rm ${params.NAME}"
                            sh "docker rmi hyunjinius/springboot:latest"
                        }


                        sh '''
                        echo 'Dockerimage build...'
                        docker build -t hyunjinius/springboot:latest .
                        '''
                    }
                }
            }
        }

        stage('Deploy'){
            steps{
                dir('backend/piece'){
                    sh '''
                    echo 'Deploy BE...'
                    docker run -d -p 0:8082 --env-file ./.env --name piece hyunjinius/springboot:latest
                    '''
                }
            }
        }
    }

    post {
            success {
            	script {
                    def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                    def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                    mattermostSend (color: 'good',
                    message: "빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                    endpoint: 'https://meeting.ssafy.com/hooks/pogn6rjjxibuppsqsiywad3oga',
                    channel: 'jenkins'
                    )
                }
            }
            failure {
            	script {
                    def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                    def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                    mattermostSend (color: 'danger',
                    message: "빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)",
                    endpoint: 'https://meeting.ssafy.com/hooks/pogn6rjjxibuppsqsiywad3oga',
                    channel: 'jenkins'
                    )
                }
            }
        }
}
